---
# Copyright (c) 2019, NVIDIA CORPORATION.  All rights reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: gpu-feature-discovery
  namespace: node-feature-discovery
  labels:
    helm.sh/chart: gpu-feature-discovery-0.5.0
    app.kubernetes.io/name: gpu-feature-discovery
    app.kubernetes.io/version: "0.5.0"
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: gpu-feature-discovery
  updateStrategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app.kubernetes.io/name: gpu-feature-discovery
    spec:
      # Mark this pod as a critical add-on; when enabled, the critical add-on
      # scheduler reserves resources for critical add-on pods so that they can
      # be rescheduled after a failure.
      # See https://kubernetes.io/docs/tasks/administer-cluster/guaranteed-scheduling-critical-addon-pods/
      priorityClassName: "system-node-critical"
      securityContext:
        {}
      containers:
        - image: nvcr.io/nvidia/gpu-feature-discovery:v0.5.0
          imagePullPolicy: IfNotPresent
          name: gpu-feature-discovery
          env:
            - name: GFD_FAIL_ON_INIT_ERROR
              value: "true"
            - name: GFD_MIG_STRATEGY
              value: "none"
            - name: GFD_NO_TIMESTAMP
              value: "false"
            - name: GFD_SLEEP_INTERVAL
              value: "60s"
          securityContext:
            privileged: true
          volumeMounts:
            - name: output-dir
              mountPath: "/etc/kubernetes/node-feature-discovery/features.d"
            - name: dmi-product-name
              mountPath: "/sys/class/dmi/id/product_name"
          resources:
            limits:
                cpu: "100m"
                memory: "128Mi"
            requests:
                cpu: "100m"
                memory: "128Mi"
      volumes:
        - name: output-dir
          hostPath:
            path: "/etc/kubernetes/node-feature-discovery/features.d"
        - name: dmi-product-name
          hostPath:
            path: "/sys/class/dmi/id/product_name"
      nodeSelector:
        feature.node.kubernetes.io/pci-10de.present: "true"
