apiVersion: v2
appVersion: 0.5.0
dependencies:
- condition: nfd.deploy
  name: node-feature-discovery
  repository: ""
  version: 0.1.0
description: A Helm chart for gpu-feature-discovery on Kubernetes
home: https://github.com/NVIDIA/gpu-feature-discovery
kubeVersion: '>= 1.10.0-0'
name: gpu-feature-discovery
type: application
version: 0.5.0
