apiVersion: v1
kind: Service
metadata:
  name: {{ include "node-feature-discovery.fullname-master" . }}
  namespace: {{ .Values.namespace.name }}
  labels:
    {{- include "node-feature-discovery.labels" . | nindent 4 }}
spec:
  selector:
    {{- include "node-feature-discovery.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/role: master
  ports:
  - name: grpc
    targetPort: grpc
    protocol: TCP
    port: {{ .Values.master.service.port }}
  type: {{ .Values.master.service.type }}
